[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.11.0"
winit = "0.28.2"
winit_input_helper = "0.14.0"
rayon = "1.7.0"
fastrand = "1.9.0"
num-complex = "0.4.3"
